### ISSUE TITLE
Excessive (but not fatal) warnings and messages for `get_geomorphology`

### ISSUE THREAD

**Issue by echelleburns** [emlab-ucsb/oceandatr#36]
While building the tests for `get_geomorphology`, I'm seeing that I'm getting a lot of warnings and messages. They're all just messages/warnings that are inherent to what we're doing, so I'm not worried about them. 

Messages: 
`Spherical geometry (s2) switched off`
`although coordinates are longitude/latitude, st_intersection assumes that they are planar` x 24
`Spherical geometry (s2) switched on`

Warning(s): `Warning messages: attribute variables are assumed to be spatially constant throughout all geometries` x 24

Wondering if we can hide them from the user, unless a fatal warning or error occurs? 
Or if we could at least limit the x24 messages and warnings? 

I've suppressed messages and warnings in the tests for this function.

**Comment by jflowernet** [comment]
Yep, good point: I've suppressed the warnings and messages for this function. @echelleburns you can remove the suppression calls from the tests when you want (probably a good idea to do so at some point just in case there are important messages/ warnings!)

**Comment by echelleburns** [comment]
Awesome, thanks! Just removed the warning and message suppression from the testthat code.
