### ISSUE TITLE
Change default `mregions_column` used by `get_area`

### ISSUE THREAD

**Issue by jflowernet** [emlab-ucsb/oceandatr#40]
Suggestion from @jaseeverett:

I was using your `get_area()` function. I wonder if the default for `mregions_column` should be  "sovereign1"  rather than "territory1" ? It seems like `sovereign1` will return all the territories of the nation, whereas territory returns the main territory with that name. So for Australia, when you use the defaults (which most people do I would guess) you only get the main island, and not any of Norfolk, Macquarie etc. I realise this may not be totally ideal for countries like France that have territories thousands of km away from the mainland, but from my perspective it would be safer to return too much info and allow the user to filter out what they don't want.
And looking at the USA, if you go with the default, you only get the mainland, and not Hawaii or Alaska (or PR etc).
`oceandatr::get_area("United States")`  vs `oceandatr::get_area("United States", mregions_column = "sovereign1")`

**Comment by echelleburns** [comment]
Just updated the function, examples, and tests to reflect this change. All tests pass, so I think we're solid, but let me know if you run into any errors

**Comment by jaseeverett** [comment]
Works for me.
